Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).


In [ ]:
def convert_units():
    print("Choose a conversion type:")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    try:
        choice = int(input("Enter your choice (1-6): "))
        value = float(input("Enter the value to convert: "))

        if choice == 1:
            result = value * 3.28084
            print(f"{value} meters is {result:.2f} feet.")
        elif choice == 2:
            result = value / 3.28084
            print(f"{value} feet is {result:.2f} meters.")
        elif choice == 3:
            result = value * 2.20462
            print(f"{value} kilograms is {result:.2f} pounds.")
        elif choice == 4:
            result = value / 2.20462
            print(f"{value} pounds is {result:.2f} kilograms.")
        elif choice == 5:
            result = value * 0.264172
            print(f"{value} liters is {result:.2f} gallons.")
        elif choice == 6:
            result = value / 0.264172
            print(f"{value} gallons is {result:.2f} liters.")
        else:
            print("Invalid choice. Please select a number from 1 to 6.")
    except ValueError:
        print("Invalid input. Please enter a numeric value.")

if __name__ == "__main__":
    convert_units()


Choose a conversion type:
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter your choice (1-6): 1
Enter the value to convert: 500
500.0 meters is 1640.42 feet.


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value

In [ ]:
def find_sum(numbers: list[float]) -> float:
    """
    Calculate the sum of a list of numbers.
    :param numbers: list of floats
    :return: float, sum of the numbers
    """
    return sum(numbers)

def find_average(numbers: list[float]) -> float:
    """
    Calculate the average of a list of numbers.
    :param numbers: list of floats
    :return: float, average of the numbers
    """
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers: list[float]) -> float:
    """
    Find the maximum value in a list of numbers.
    :param numbers: list of floats
    :return: float, maximum value
    """
    return max(numbers)

def find_minimum(numbers: list[float]) -> float:
    """
    Find the minimum value in a list of numbers.
    :param numbers: list of floats
    :return: float, minimum value
    """
    return min(numbers)

def main():
    """
    Prompt user for a list of numbers and perform selected mathematical operation.
    """
    try:
        print("Choose an operation:")
        print("1. Find Sum")
        print("2. Find Average")
        print("3. Find Maximum")
        print("4. Find Minimum")

        choice = int(input("Enter your choice (1-4): "))
        numbers = list(map(float, input("Enter a list of numbers separated by spaces: ").split()))

        if not numbers:
            print("Error: The list cannot be empty.")
            return

        if choice == 1:
            print(f"Sum: {find_sum(numbers)}")
        elif choice == 2:
            print(f"Average: {find_average(numbers)}")
        elif choice == 3:
            print(f"Maximum: {find_maximum(numbers)}")
        elif choice == 4:
            print(f"Minimum: {find_minimum(numbers)}")
        else:
            print("Invalid choice. Please select a valid option.")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")

if __name__ == "__main__":
    main()


Choose an operation:
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Enter your choice (1-4): 3
Enter a list of numbers separated by spaces: 44 35 99
Maximum: 99.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst: list) -> list:
    return lst[::2]

def main():

    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return
        print(f"Every Other Element: {extract_every_other(numbers)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")

if __name__ == "__main__":
    main()


Enter a list of numbers separated by spaces: 11 12 13 14 15
Every Other Element: [11, 13, 15]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

–Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].


In [ ]:
def extract_every_other(lst: list) -> list:

    return lst[::2]

def get_sublist(lst: list, start: int, end: int) -> list:

    return lst[start:end+1]

def main():

    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return

        print(f"Every Other Element: {extract_every_other(numbers)}")

        start = int(input("Enter start index for sublist: "))
        end = int(input("Enter end index for sublist: "))
        print(f"Sublist: {get_sublist(numbers, start, end)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")

if __name__ == "__main__":
    main()


Enter a list of numbers separated by spaces: 11 12 13 14 15 16 17
Every Other Element: [11, 13, 15, 17]
Enter start index for sublist: 1
Enter end index for sublist: 5
Sublist: [12, 13, 14, 15, 16]


3.Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].


In [ ]:
def reverse_list(lst: list) -> list:

    return lst[::-1]

def main():

    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return

        print(f"Reversed List: {reverse_list(numbers)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")

if __name__ == "__main__":
    main()


Enter a list of numbers separated by spaces: 11 12 13 14 15
Reversed List: [15, 14, 13, 12, 11]


4.Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst: list) -> list:

    return lst[1:-1] if len(lst) > 2 else []

def main():

    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return

        print(f"List without first and last elements: {remove_first_last(numbers)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")

if __name__ == "__main__":
    main()


Enter a list of numbers separated by spaces: 11 12 13 14 15 16
List without first and last elements: [12, 13, 14, 15]


5.Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst: list, n: int) -> list:

    return lst[:n] if n > 0 else []

def main():
    """
    Prompt user for a list of numbers and return modified sublists.
    """
    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return

        n = int(input("Enter the number of first elements to extract: "))
        print(f"First {n} elements: {get_first_n(numbers, n)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")

if __name__ == "__main__":
    main()

Enter a list of numbers separated by spaces: 10 11 13 14 15
Enter the number of first elements to extract: 2
First 2 elements: [10, 11]


6.Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst: list, n: int) -> list:
    return lst[-n:] if n > 0 else []

def main():
    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return

        n = int(input("Enter the number of last elements to extract: "))
        print(f"Last {n} elements: {get_last_n(numbers, n)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")

if __name__ == "__main__":
    main()


Enter a list of numbers separated by spaces: 11 23 455 67
Enter the number of last elements to extract: 3
Last 3 elements: [23, 455, 67]


7.Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].


In [ ]:
def reverse_skip(lst: list) -> list:
    return lst[-2::-2]

def main():
    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return

        print(f"Elements in reverse order (skipping one): {reverse_skip(numbers)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")

if __name__ == "__main__":
    main()


Enter a list of numbers separated by spaces: 11 23 12 13 14
Elements in reverse order (skipping one): [13, 23]


1.Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].


In [ ]:
def flatten(lst: list) -> list:
    return [item for sublist in lst for item in sublist]

def main():

    try:
        nested_list = eval(input("Enter a nested list (e.g., [[1,2],[3,4],[5]]): "))
        if not isinstance(nested_list, list) or not all(isinstance(sub, list) for sub in nested_list):
            print("Error: Please enter a valid nested list.")
            return

        print(f"Flattened List: {flatten(nested_list)}")
    except Exception as e:
        print(f"Invalid input: {e}")

if __name__ == "__main__":
    main()


Enter a nested list (e.g., [[1,2],[3,4],[5]]): [[1,2],[3,4],[5]]
Flattened List: [1, 2, 3, 4, 5]


2.Accessing Nested List Elements:

 Write a Python function that extracts a specific element from a nested list given its indices.


 • Requirements:

 – Define a function access nested
 element(lst, indices) that takes a nested list lst and
 a list of indices indices, and returns the element at that position.– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
 2], the output should be 6.

In [ ]:
def access_nested_element(lst: list, indices: list) -> int:
    try:
        element = lst
        for index in indices:
            element = element[index]
        return element
    except (IndexError, TypeError):
        return "Error: Invalid indices or structure."

def main():
    try:
        nested_list = eval(input("Enter a nested list (e.g., [[1,2,3],[4,5,6],[7,8,9]]): "))
        indices = list(map(int, input("Enter indices separated by spaces (e.g., 1 2): ").split()))

        print(f"Accessed Element: {access_nested_element(nested_list, indices)}")
    except Exception as e:
        print(f"Invalid input: {e}")

if __name__ == "__main__":
    main()


Enter a nested list (e.g., [[1,2,3],[4,5,6],[7,8,9]]): [[1,2,3],[4,5,6],[7,8,9]]
Enter indices separated by spaces (e.g., 1 2): 1 2
Accessed Element: 6


 3. Sum of All Elements in a Nested List:

 Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

 • Requirements:

 – Define a function sum
 nested(lst) that takes a nested list lst and returns the sum of all
 the elements.

 – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst: list) -> int:
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum nested lists
        else:
            total += item  # Add number to total
    return total

def main():
    try:
        nested_list = eval(input("Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): "))
        print(f"Sum of all elements: {sum_nested(nested_list)}")
    except Exception as e:
        print(f"Invalid input: {e}")

if __name__ == "__main__":
    main()


Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): [[1,2],[3,[4,5]],6]
Sum of all elements: 21


4.Remove Specific Element from a Nested List:

 Write a Python function that removes all occurrences of a specific element from a nested list.

 • Requirements:

 – Define a function remove
 element(lst, elem) that removes elem from lst and returns the
 modified list.

 – Example: Fortheinput lst = [[1, 2], [3, 2], [4, 5]]andelem = 2,theoutputshould
 be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst: list, elem: int) -> list:
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))  # Recursively process nested lists
        elif item != elem:
            result.append(item)  # Add non-matching elements
    return result

def main():
    try:
        nested_list = eval(input("Enter a nested list (e.g., [[1,2],[3,2],[4,5]]): "))
        elem = int(input("Enter the element to remove: "))
        print(f"Modified List: {remove_element(nested_list, elem)}")
    except Exception as e:
        print(f"Invalid input: {e}")

if __name__ == "__main__":
    main()


Enter a nested list (e.g., [[1,2],[3,2],[4,5]]): [[1,2],[3,2],[4,5],7]
Enter the element to remove: 1
Modified List: [[2], [3, 2], [4, 5], 7]


 5. Find the Maximum Element in a Nested List:

 Write a Python function that finds the maximum element in a nested list (regardless of depth).

 • Requirements:

 – Define a function find
 element.
 max(lst) that takes a nested list lst and returns the maximum
 – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max_element(lst: list) -> int:
    max_value = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max_element(item))  # Recursively find max in nested lists
        else:
            max_value = max(max_value, item)  # Compare numbers directly
    return max_value

def main():
    try:
        nested_list = eval(input("Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): "))
        print(f"Maximum Element: {find_max_element(nested_list)}")
    except Exception as e:
        print(f"Invalid input: {e}")

if __name__ == "__main__":
    main()


Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): [[1,2],[3,[4,5]],6]
Maximum Element: 6


 6. Count Occurrences of an Element in a Nested List:

 Write a Python function that counts how many times a specific element appears in a nested list.

 • Requirements:

 – Define a function count
occurrences(lst, elem) that counts the occurrences of elem in
 the nested list lst.– Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,theoutputshould
 be 3.

In [ ]:
def count_occurrences(lst: list, elem: int) -> int:

    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count occurrences in nested lists
        elif item == elem:
            count += 1  # Increment count if element matches
    return count

def main():
    try:
        nested_list = eval(input("Enter a nested list (e.g., [[1,2],[2,3],[2,4]]): "))
        elem = int(input("Enter the element to count: "))
        print(f"Occurrences of {elem}: {count_occurrences(nested_list, elem)}")
    except Exception as e:
        print(f"Invalid input: {e}")

if __name__ == "__main__":
    main()


Enter a nested list (e.g., [[1,2],[2,3],[2,4]]): [[1,2],[2,3],[2,4]]
Enter the element to count: 5
Occurrences of 5: 0


 7. Flatten a List of Lists of Lists:
 Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

 • Requirements:

 – Define a function deep
 flatten(lst) that takes a deeply nested list lst and returns a single
 flattened list.

 – Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
 [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst: list) -> list:
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))  # Recursively flatten nested lists
        else:
            result.append(item)  # Add non-list elements directly
    return result

def main():
    try:
        nested_list = eval(input("Enter a deeply nested list (e.g., [[[1,2],[3,4]],[[5,6],[7,8]]]): "))
        print(f"Flattened List: {deep_flatten(nested_list)}")
    except Exception as e:
        print(f"Invalid input: {e}")

if __name__ == "__main__":
    main()


Enter a deeply nested list (e.g., [[[1,2],[3,4]],[[5,6],[7,8]]]): [[[1,2],[3,4]],[[5,6],[7,8]]]
Flattened List: [1, 2, 3, 4, 5, 6, 7, 8]


 8. Nested List Average:
 Write a Python function that calculates the average of all elements in a nested list.

 • Requirements:

 – Define a function average
 of all the elements.
 nested(lst) that takes a nested list lst and returns the average

 – Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be

In [ ]:
def nested_average(lst: list) -> float:
    def flatten(lst):
        result = []
        for item in lst:
            if isinstance(item, list):
                result.extend(flatten(item))  # Recursively flatten nested lists
            else:
                result.append(item)  # Add non-list elements directly
        return result

    flat_list = flatten(lst)  # Flatten the list first
    return sum(flat_list) / len(flat_list) if flat_list else 0

def main():
    try:
        nested_list = eval(input("Enter a deeply nested list (e.g., [[[1,2],[3,4]],[[5,6],[7,8]]]): "))
        print(f"Average of Elements: {nested_average(nested_list)}")
    except Exception as e:
        print(f"Invalid input: {e}")

if __name__ == "__main__":
    main()


Enter a deeply nested list (e.g., [[[1,2],[3,4]],[[5,6],[7,8]]]): [[[1,2],[3,4]],[[5,6],[7,8]]]
Average of Elements: 4.5


 Problem- 1: Array Creation:
 Complete the following Tasks:
 1. Initialize an empty array with size 2X2.
 2. Initialize an all one array with size 4X2.
 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [12]:
import numpy as np

def array_operations():
    """
    Perform basic array creation tasks using NumPy.
    """
    # 1. Initialize an empty array with size 2x2
    empty_array = np.empty((2, 2))
    print("Empty 2x2 Array:\n", empty_array)

    # 2. Initialize an all-ones array with size 4x2
    ones_array = np.ones((4, 2))
    print("All Ones 4x2 Array:\n", ones_array)

    # 3. Return a new array of given shape and type, filled with fill value
    fill_value_array = np.full((3, 3), 7)  # Example: Filling with 7
    print("Filled 3x3 Array:\n", fill_value_array)

    # 4. Return a new array of zeros with same shape and type as a given array
    reference_array = np.array([[1, 2, 3], [4, 5, 6]])
    zeros_like_array = np.zeros_like(reference_array)
    print("Zeros Like Given Array:\n", zeros_like_array)

    # 5. Return a new array of ones with same shape and type as a given array
    ones_like_array = np.ones_like(reference_array)
    print("Ones Like Given Array:\n", ones_like_array)

    # 6. Convert an existing list to a NumPy array
    new_list = [1, 2, 3, 4]
    numpy_array = np.array(new_list)
    print("Converted NumPy Array:\n", numpy_array)

def main():
    """
    Execute array operations.
    """
    array_operations()

if __name__ == "__main__":
    main()


Empty 2x2 Array:
 [[2.26036392e-316 0.00000000e+000]
 [0.00000000e+000 2.44029516e-312]]
All Ones 4x2 Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Filled 3x3 Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros Like Given Array:
 [[0 0 0]
 [0 0 0]]
Ones Like Given Array:
 [[1 1 1]
 [1 1 1]]
Converted NumPy Array:
 [1 2 3 4]


Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:
 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
 2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}
 3. Create a 3X3 identity matrix.{Hint:np.eye()}
 4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}
 5. Create a 10X10 array with random values and find the minimum and maximum values.
 6. Create a zero array of size 10 and replace 5th element with 1.
 7. Reverse an array arr = [1,2,0,0,4,0].
 8. Create a 2d array with 1 on border and 0 inside.
 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [13]:

def array_manipulation():
    # 1. Create an array with values ranging from 10 to 49
    range_array = np.arange(10, 50)
    print("Array with values from 10 to 49:\n", range_array)

    # 2. Create a 3x3 matrix with values ranging from 0 to 8
    reshaped_matrix = np.arange(9).reshape(3, 3)
    print("3x3 Matrix with values from 0 to 8:\n", reshaped_matrix)

    # 3. Create a 3x3 identity matrix
    identity_matrix = np.eye(3)
    print("3x3 Identity Matrix:\n", identity_matrix)

    # 4. Create a random array of size 30 and find the mean
    random_array = np.random.random(30)
    mean_value = random_array.mean()
    print("Mean of Random Array:\n", mean_value)

    # 5. Create a 10x10 array with random values and find min/max values
    random_matrix = np.random.random((10, 10))
    min_value = random_matrix.min()
    max_value = random_matrix.max()
    print("Min Value of 10x10 Random Matrix:\n", min_value)
    print("Max Value of 10x10 Random Matrix:\n", max_value)

    # 6. Create a zero array of size 10 and replace the 5th element with 1
    zero_array = np.zeros(10)
    zero_array[4] = 1
    print("Zero Array with 5th Element as 1:\n", zero_array)

    # 7. Reverse an array
    arr = np.array([1, 2, 0, 0, 4, 0])
    reversed_arr = arr[::-1]
    print("Reversed Array:\n", reversed_arr)

    # 8. Create a 2D array with 1 on the border and 0 inside
    border_array = np.ones((5, 5))
    border_array[1:-1, 1:-1] = 0
    print("2D Array with 1 on Border and 0 Inside:\n", border_array)

    # 9. Create an 8x8 matrix and fill it with a checkerboard pattern
    checkerboard = np.zeros((8, 8), dtype=int)
    checkerboard[1::2, ::2] = 1
    checkerboard[::2, 1::2] = 1
    print("8x8 Checkerboard Pattern:\n", checkerboard)

def main():
    array_manipulation()

if __name__ == "__main__":
    main()


Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean of Random Array:
 0.45885472747424566
Min Value of 10x10 Random Matrix:
 0.01618951533943125
Max Value of 10x10 Random Matrix:
 0.9826494495461593
Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed Array:
 [0 4 0 0 2 1]
2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem- 3: Array Operations:

 For the following arrays:

 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

 v = np.array([9,10]) and w = np.array([11,12]);

 Complete all the task using numpy:
 1. Add the two array.
 2. Subtract the two array.
 3. Multiply the array with any integers of your choice.
 4. Find the square of each element of the array.
 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.
 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [14]:

def array_operations():
    x = np.array([[1, 2], [3, 5]])
    y = np.array([[5, 6], [7, 8]])
    v = np.array([9, 10])
    w = np.array([11, 12])

    # 1. Add the two arrays
    addition = x + y
    print("Addition of x and y:\n", addition)

    # 2. Subtract the two arrays
    subtraction = x - y
    print("Subtraction of x and y:\n", subtraction)

    # 3. Multiply the array with any integer (e.g., 3)
    multiplied_array = x * 3
    print("Multiplication of x by 3:\n", multiplied_array)

    # 4. Find the square of each element of the array
    squared_array = x ** 2
    print("Square of each element in x:\n", squared_array)

    # 5. Find the dot product
    dot_vw = np.dot(v, w)
    dot_xv = np.dot(x, v)
    dot_xy = np.dot(x, y)
    print("Dot product of v and w:\n", dot_vw)
    print("Dot product of x and v:\n", dot_xv)
    print("Dot product of x and y:\n", dot_xy)

    # 6. Concatenate x and y along rows, and v and w along columns
    concat_xy = np.concatenate((x, y), axis=0)
    concat_vw = np.column_stack((v, w))
    print("Concatenation of x and y along rows:\n", concat_xy)
    print("Concatenation of v and w along columns:\n", concat_vw)

    # 7. Attempt to concatenate x and v; observe the error
    try:
        concat_xv = np.concatenate((x, v), axis=0)
        print("Concatenation of x and v:\n", concat_xv)
    except ValueError as e:
        print("Error while concatenating x and v:\n", e)

def main():
    """
    Execute array operations.
    """
    array_operations()

if __name__ == "__main__":
    main()


Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]
Square of each element in x:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w:
 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]
Error while concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem- 4: Matrix Operations:

 • For the following arrays:

 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

 Prove following with Numpy:

 1. Prove A.A−1 = I.
 2. Prove AB= BA.
 3. Prove (AB)T = BTAT.
 • Solve the following system of Linear equation using Inverse Methods.

 2x −3y+z =−1

 x −y+2z =−3

 3x +y−z =9

 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func
tion of Numpy}

In [15]:
import numpy as np

def matrix_operations():
    """
    Perform matrix operations using NumPy.
    """
    A = np.array([[3, 4], [7, 8]])
    B = np.array([[5, 3], [2, 1]])

    # 1. Prove A * A⁻¹ = I
    A_inv = np.linalg.inv(A)
    identity_matrix = np.dot(A, A_inv)
    print("A * A⁻¹ (Should be Identity Matrix):\n", np.round(identity_matrix, decimals=6))

    # 2. Prove AB = BA
    AB = np.dot(A, B)
    BA = np.dot(B, A)
    print("AB:\n", AB)
    print("BA:\n", BA)
    print("Is AB equal to BA?", np.allclose(AB, BA))

    # 3. Prove (AB)ᵀ = Bᵀ Aᵀ
    AB_T = np.transpose(AB)
    BT_AT = np.dot(np.transpose(B), np.transpose(A))
    print("(AB)ᵀ:\n", AB_T)
    print("Bᵀ Aᵀ:\n", BT_AT)
    print("Is (AB)ᵀ equal to Bᵀ Aᵀ?", np.allclose(AB_T, BT_AT))

    # Solve system of equations using inverse method
    A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
    B_eq = np.array([-1, -3, 9])
    X = np.linalg.inv(A_eq).dot(B_eq)
    print("Solution of the system (AX = B):\n", X)

    # Solve using np.linalg.solve (recommended method)
    X_solve = np.linalg.solve(A_eq, B_eq)
    print("Solution using np.linalg.solve:\n", X_solve)

def main():
    matrix_operations()

if __name__ == "__main__":
    main()


A * A⁻¹ (Should be Identity Matrix):
 [[1. 0.]
 [0. 1.]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA? False
(AB)ᵀ:
 [[23 51]
 [13 29]]
Bᵀ Aᵀ:
 [[23 51]
 [13 29]]
Is (AB)ᵀ equal to Bᵀ Aᵀ? True
Solution of the system (AX = B):
 [ 2.  1. -2.]
Solution using np.linalg.solve:
 [ 2.  1. -2.]
